openapi: 3.0.2
info:
  title: Code WP
  version: 1.0.0
servers:
  - url: http://localhost
paths:
  "/api/packages/{package}/files":
    get:
      summary: Display a listing of the resource.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
    post:
      summary: Store a newly created resource in storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
  "/api/packages/{package}/files/{file}":
    get:
      summary: Display the specified resource.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
    put:
      summary: Update the specified resource in storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
    delete:
      summary: Remove the specified resource from storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
  "/spa/packages/{package}/files":
    get:
      summary: Display a listing of the resource.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
    post:
      summary: Store a newly created resource in storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
  "/spa/packages/{package}/files/{file}":
    get:
      summary: Display the specified resource.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
    put:
      summary: Update the specified resource in storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
    delete:
      summary: Remove the specified resource from storage.
      parameters:
        - name: package
          in: path
          required: true
          schema:
            type: string
        - name: file
          in: path
          required: true
          schema:
            type: string
